package com.cgk.game.event;

public enum EventType {
	CARD_DISCARDED, PLAY, ADD_BUFF, MULT_BUFF, DEBUFF, END_HERO_TURN, END_ENEMY_TURN, ATTACK_PLAYER, ATTACK_ENEMY, DEFEAT, DEAD_ENEMY, RANDOM_DISCARD, DRAWN_CARD, SUPER_COMBO, TYPE_COMBO, RESOURCE_COMBO_EVENT, DROP_COMBO, UNREGISTER
}
